project:
  type: book
  output-dir: docs

book:
  title: "Introducción a la Economía"
  author: "Frank Fuentes, Julio Andujar y Oscar Pascual"
  date: "3/6/2026"
  chapters:
    - index.qmd
    - part: "Fundamentos"
      chapters:
        - cap1.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt
