project:
  type: book
  output-dir: docs

book:
  title: "Introducción a la Economía"
  author: "Frank Fuentes, Julio Andujar y Oscar Pascual"
  date: "3/6/2026"
  navbar:
    logo: https://empirica.do/wp-content/media/2017/03/logo.png
  chapters:
    - index.qmd
    - part: "Fundamentos"
      chapters:
        - cap1.qmd
        - cap2.qmd
        - cap3.qmd
    - part: "Microeconomía"
      chapters:
        - cap4.qmd

bibliography: references.bib

format:
  html:
    css: styles.css
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt

lang: es
